# Generated by Django 2.1.8 on 2019-05-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Episode',
        ),
    ]
